// Admin auth + content mutations, delegated to the build-selected backend.
export {
  getSession,
  signIn,
  signOut,
  isAdmin,
  changePassword,
  setTestimonialStatus,
  updateTestimonial,
  updatePerson,
  deleteTestimonial,
  setTestimonialTags,
  fetchAllComments,
  setCommentStatus,
  deleteComment,
  addFilterOption,
  deleteFilterOption,
  upsertSetting,
  fetchAllSuccessStories,
  createStory,
  updateStory,
  deleteStory,
  setStoryChildren,
  fetchAdminProjectNames,
} from '@backend';
